INFO  | File run_exp_local.py     | Line 16    | Writing log file to ./exp/GTS_1_0310_120252/log_exp_1010.txt
INFO  | File run_exp_local.py     | Line 17    | Exp instance id = GTS_1_0310_120252
ERROR | File run_exp_local.py     | Line 25    | Traceback (most recent call last):
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/run_exp_local.py", line 21, in main
    runner.train()
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/runner/GTS_runner.py", line 109, in train
    _, outputs = self.model(data_batch.x, data_batch.y, self.entire_inputs, self.init_edge_index)
  File "/opt/anaconda3/envs/GSL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/models/GTS/GTS_model.py", line 86, in forward
    print(adj.shape)
AttributeError: 'tuple' object has no attribute 'shape'

